### ISSUE TITLE
Why not make mokku repo public?

### ISSUE THREAD

**Issue by fastndead** [mukuljainx/mokku-bug-trakcer#2]
Since it's a Chrome extension it doesn't make much sense to keep the repo private since the source code is still accessible for users. I think it would greatly benefit the project to make it open source, I personally would love to contribute to the extension, so I'm wondering why not make the Mokku repo public?

**Comment by avivasyuta** [comment]
I was also very surprised when the author deleted all the sources of the extension, because they were previously on Github. Now this extension doesn't inspire confidence in me because it's not at all clear what it does under the hood.

**Comment by richrd** [comment]
> I was also very surprised when the author deleted all the sources of the extension, because they were previously on Github. Now this extension doesn't inspire confidence in me because it's not at all clear what it does under the hood.

Very much same feelings here too. A bit disappointed honestly but of course the author is free to do with their code what ever they want. Luckily there are plenty of other alternatives available.

**Comment by fastndead** [comment]
@richrd can you point me to some open-source alternatives?

**Comment by avivasyuta** [comment]
@fastndead mockiato
https://chrome.google.com/webstore/detail/mockiato-mocks-on-the-fly/ilbkkhmnmnehcicempfpekgcpneeekao

**Comment by mukuljainx** [comment]
Hello everyone, reason behind making it private was to enable premium features to monetize it or sell it as there was not much support and it takes a lot of time. I have dropped this idea due to lack of time and making it public again. Consider donating to support the future development.
